# Generated by Django 5.0.12 on 2025-04-02 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='old_user_id',
            field=models.IntegerField(default=0),
        ),
    ]
